require 'hoe'
require './lib/solidity/version.rb'

Hoe.spec 'solidity' do

  self.version = Solidity::VERSION

  self.summary = "solidity - type-safe (crypto) contracts"
  self.description = summary

  self.urls    = ['https://github.com/s6ruby/ruby-to-solidity']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
